# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: (_version.py|versioneer.py|generated)

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black

-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter
        args: [--in-place]

-   repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
        args:
        - --ignore-imports=yes

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: (_version.py|versioneer.py)
