# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: (generated|.params)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.3"
    hooks:
      - id: ruff-format
        args:
          - --config=./pyproject.toml
      - id: ruff
        args:
          - --config=./pyproject.toml
          - --fix

  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
        args: [] # Do not auto-fix

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [types-protobuf, types-PyYAML, types-retry]
        args:
          - --check-untyped-defs
