# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: (generated|.params)

repos:
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.2
      hooks:
          - id: pyupgrade
            args:
                - --py39-plus

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-ast
          - id: check-case-conflict

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: "v0.4.4"
      hooks:
          - id: ruff-format
            args:
                - --config=./pyproject.toml
          - id: ruff
            args:
                - --config=./pyproject.toml

    - repo: https://github.com/crate-ci/typos
      rev: v1.21.0
      hooks:
          - id: typos
            args: [] # Do not auto-fix

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            additional_dependencies: [types-protobuf, types-PyYAML, types-retry]
            args:
                - --check-untyped-defs
