# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: (generated|.params)

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
    -   id: pyupgrade
        args:
        - --py39-plus

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict

-   repo: https://github.com/crate-ci/typos
    rev: v1.16.1
    hooks:
      - id: typos
        args:
            [] # Do not auto-fix

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-protobuf, types-PyYAML, types-retry]
        args:
        - --check-untyped-defs

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.280'
    hooks:
    -   id: ruff
