# This workflow will run pytest on this package.

name: Test Python package with pytest

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Install package
        run: poetry install

      - name: Test package
        run: poetry run pytest
