# This workflow will run pytest on this package.

name: Test Python package with pytest

on:
  push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install poetry-dynamic-versioning

    - name: Install package
      run: poetry install

    - name: Test package
      run: poetry run pytest
