# This workflow will upload a Python Package using poetry when a release is created

name: Upload Python Package

# on:
#   release:
#     types: [published]

on:
  push:
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Build package
      # Only build the source distribution, as the wheel is going to be built by piwheels.
      run: poetry build --format sdist

    - name: Publish package
      run: |
        poetry config http-basic.pypi "__token__" "${{ secrets.PYPI_API_TOKEN }}"
        poetry publish
